from __future__ import annotations

import hashlib
import json
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Sequence

from .data_loader import DocumentIngestionPipeline
from .embeddings import EmbeddingManager
from .store import VectorStore
from .text import split_documents

LOGGER = logging.getLogger("rag_v2.smart_indexing")


@dataclass(slots=True)
class FileFingerprint:
    """Snapshot metadata for one source file used for incremental indexing."""

    path: str
    mtime_ns: int
    size: int
    sha256: str


@dataclass(slots=True)
class IndexState:
    """Persisted state used to detect file-level changes."""

    files: Dict[str, FileFingerprint]
    chunk_size: int
    chunk_overlap: int


@dataclass(slots=True)
class IndexPlan:
    """Execution plan generated by comparing filesystem and saved index state."""

    new_files: List[Path]
    modified_files: List[Path]
    unchanged_files: List[Path]
    deleted_files: List[str]
    requires_reindex: bool


@dataclass(slots=True)
class IndexingSummary:
    """Indexing result returned to the caller."""

    indexed_files: int
    indexed_chunks: int
    reused_existing_index: bool
    removed_files: int


class IndexStateStore:
    """JSON-backed state store for incremental indexing fingerprints."""

    def __init__(self, state_path: Path):
        self.state_path = state_path
        self.state_path.parent.mkdir(parents=True, exist_ok=True)

    def load(self) -> IndexState:
        if not self.state_path.exists():
            return IndexState(files={}, chunk_size=0, chunk_overlap=0)

        raw = json.loads(self.state_path.read_text(encoding="utf-8"))
        files = {
            path: FileFingerprint(
                path=path,
                mtime_ns=int(snapshot.get("mtime_ns", 0)),
                size=int(snapshot.get("size", 0)),
                sha256=str(snapshot.get("sha256", "")),
            )
            for path, snapshot in (raw.get("files") or {}).items()
        }
        return IndexState(
            files=files,
            chunk_size=int(raw.get("chunk_size", 0)),
            chunk_overlap=int(raw.get("chunk_overlap", 0)),
        )

    def save(self, state: IndexState) -> None:
        payload = {
            "chunk_size": state.chunk_size,
            "chunk_overlap": state.chunk_overlap,
            "files": {
                path: {
                    "mtime_ns": snapshot.mtime_ns,
                    "size": snapshot.size,
                    "sha256": snapshot.sha256,
                }
                for path, snapshot in state.files.items()
            },
        }
        self.state_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


class SmartIndexer:
    """Incremental indexer that embeds only new or changed source files."""

    def __init__(
        self,
        data_dir: Path,
        ingestion_pipeline: DocumentIngestionPipeline,
        embedding_manager: EmbeddingManager,
        vector_store: VectorStore,
        state_store: IndexStateStore,
        chunk_size: int,
        chunk_overlap: int,
    ):
        self.data_dir = data_dir.resolve()
        self.ingestion_pipeline = ingestion_pipeline
        self.embedding_manager = embedding_manager
        self.vector_store = vector_store
        self.state_store = state_store
        self.chunk_size = chunk_size
        self.chunk_overlap = chunk_overlap

    @staticmethod
    def _sha256(path: Path) -> str:
        hasher = hashlib.sha256()
        with path.open("rb") as fh:
            for block in iter(lambda: fh.read(1024 * 1024), b""):
                hasher.update(block)
        return hasher.hexdigest()

    def _list_supported_files(self) -> List[Path]:
        allowed = set(self.ingestion_pipeline.SUPPORTED_EXTENSIONS)
        return sorted(p for p in self.data_dir.glob("**/*") if p.is_file() and p.suffix.lower() in allowed)

    def _fingerprint_files(self, files: Sequence[Path], previous: Dict[str, FileFingerprint]) -> Dict[str, FileFingerprint]:
        snapshots: Dict[str, FileFingerprint] = {}
        for path in files:
            stat = path.stat()
            key = str(path.resolve())
            old = previous.get(key)
            if old and old.mtime_ns == stat.st_mtime_ns and old.size == stat.st_size:
                snapshots[key] = old
                continue

            snapshots[key] = FileFingerprint(
                path=key,
                mtime_ns=stat.st_mtime_ns,
                size=stat.st_size,
                sha256=self._sha256(path),
            )
        return snapshots

    def plan(self, force_reindex: bool = False) -> tuple[IndexPlan, Dict[str, FileFingerprint]]:
        previous = self.state_store.load()
        files = self._list_supported_files()
        current_snapshots = self._fingerprint_files(files, previous.files)

        if force_reindex:
            return (
                IndexPlan(
                    new_files=files,
                    modified_files=[],
                    unchanged_files=[],
                    deleted_files=list(set(previous.files.keys()) - set(current_snapshots.keys())),
                    requires_reindex=True,
                ),
                current_snapshots,
            )

        cfg_changed = previous.chunk_size != self.chunk_size or previous.chunk_overlap != self.chunk_overlap

        new_files: List[Path] = []
        modified_files: List[Path] = []
        unchanged_files: List[Path] = []

        for path in files:
            key = str(path.resolve())
            old = previous.files.get(key)
            now = current_snapshots[key]
            if old is None:
                new_files.append(path)
            elif old.sha256 != now.sha256:
                modified_files.append(path)
            else:
                unchanged_files.append(path)

        deleted = list(set(previous.files.keys()) - set(current_snapshots.keys()))

        if cfg_changed:
            LOGGER.info("Chunking configuration changed; full reindex required.")
            return (
                IndexPlan(
                    new_files=files,
                    modified_files=[],
                    unchanged_files=[],
                    deleted_files=deleted,
                    requires_reindex=True,
                ),
                current_snapshots,
            )

        return (
            IndexPlan(
                new_files=new_files,
                modified_files=modified_files,
                unchanged_files=unchanged_files,
                deleted_files=deleted,
                requires_reindex=False,
            ),
            current_snapshots,
        )

    def run(self, force_reindex: bool = False) -> IndexingSummary:
        plan, current_snapshots = self.plan(force_reindex=force_reindex)
        changed_files = plan.new_files + plan.modified_files

        if plan.requires_reindex:
            self.vector_store.reset_collection()
            changed_files = plan.new_files

        for deleted in plan.deleted_files:
            self.vector_store.delete_by_source(deleted)

        if not changed_files and not plan.deleted_files:
            LOGGER.info("No new or modified files detected; reusing existing vector index.")
            return IndexingSummary(indexed_files=0, indexed_chunks=0, reused_existing_index=True, removed_files=0)

        indexed_chunks = 0
        if changed_files:
            docs, report = self.ingestion_pipeline.load_file_paths(changed_files)
            LOGGER.info(
                "Changed file ingestion complete. files=%s loaded=%s failed=%s docs=%s",
                report.total_files,
                report.loaded_files,
                report.failed_files,
                report.total_documents,
            )

            chunks = split_documents(docs, chunk_size=self.chunk_size, chunk_overlap=self.chunk_overlap)
            if chunks:
                for path in changed_files:
                    self.vector_store.delete_by_source(str(path.resolve()))

                vectors = self.embedding_manager.embed_documents([chunk.page_content for chunk in chunks])
                self.vector_store.add_documents(chunks, vectors)
                indexed_chunks = len(chunks)

        new_state = IndexState(files=current_snapshots, chunk_size=self.chunk_size, chunk_overlap=self.chunk_overlap)
        self.state_store.save(new_state)

        return IndexingSummary(
            indexed_files=len(changed_files),
            indexed_chunks=indexed_chunks,
            reused_existing_index=not changed_files,
            removed_files=len(plan.deleted_files),
        )
